#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "game/farcall_helpers.h"

#include "mist/geo.inc.c"
#include "explosion/geo.inc.c"
#include "butterfly/geo.inc.c"
#include "coin/geo.inc.c"
#include "warp_pipe/geo.inc.c"
#include "door/geo.inc.c"
#include "bowser_key/geo.inc.c"
#include "flame/geo.inc.c"
#include "blue_fish/geo.inc.c"
#include "leaves/geo.inc.c"
#include "mario_cap/geo.inc.c"
#include "number/geo.inc.c"
#include "mushroom_1up/geo.inc.c"
#include "star/geo.inc.c"
#include "dirt/geo.inc.c"
#include "transparent_star/geo.inc.c"
#include "white_particle/geo.inc.c"
#include "wooden_signpost/geo.inc.c"
#include "tree/geo.inc.c"

#include "game/behaviors/explosion.inc.c"
#include "game/behaviors/butterfly.inc.c"
#include "game/behaviors/triplet_butterfly.inc.c"
#include "game/behaviors/red_coin.inc.c"
#include "game/behaviors/coin.inc.c"
#include "game/behaviors/moving_coin.inc.c"
#include "game/behaviors/door.inc.c"
#include "game/behaviors/bowser_key.inc.c"
#include "game/behaviors/bowser_key_cutscene.inc.c"
#include "game/behaviors/bouncing_fireball.inc.c"
#include "game/behaviors/flamethrower.inc.c"
#include "game/behaviors/lll_rotating_hex_flame.inc.c"
#include "game/behaviors/lll_volcano_flames.inc.c"
#include "game/behaviors/blue_fish.inc.c"
#include "game/behaviors/tree_particles.inc.c"
#include "game/behaviors/cap.inc.c"
#include "game/behaviors/orange_number.inc.c"
#include "game/behaviors/mushroom_1up.inc.c"
#include "game/behaviors/reds_star_marker.inc.c"
#include "game/behaviors/celebration_star.inc.c"
#include "game/behaviors/fire_piranha_plant.inc.c"
#include "game/behaviors/flame.inc.c"
#include "game/behaviors/cloud.inc.c"

#include "game/behaviors/pole.inc.c"
#include "game/behaviors/water_objs.inc.c"
#include "game/behaviors/warp.inc.c"
#include "game/behaviors/water_mist.inc.c"
#include "game/behaviors/tumbling_bridge.inc.c"
#include "game/behaviors/fish.inc.c"
#include "game/behaviors/sound_spawner.inc.c"
#include "game/behaviors/pole_base.inc.c"
#ifndef VERSION_JP
#include "game/behaviors/music_touch.inc.c"
#endif